[package]
name = "console"
version = "0.1.0"
edition = "2021"

[dependencies]

crankshaft-monitor = { path = "../crankshaft-monitor", version = "0.1.0" }
crankshaft-engine = { path = "../crankshaft-engine", version = "0.4.0" }

clap = { version = "~4.5.4", features = [
    "wrap_help",
    "cargo",
    "derive",
    "env",
] }
clap_complete = "~4.5.2"
ratatui = { version = "0.26.2", default-features = false, features = [
    "crossterm",
] }
anyhow = "1.0.75"
crossterm = { version = "0.27.0", features = ["event-stream"] }
color-eyre = { version = "0.6", features = ["issue-url"] }
serde = { version = "1.0.145", features = ["derive"] }
tonic.workspace = true
tracing.workspace = true
tokio.workspace = true
futures-util.workspace = true
tower = "0.5.2"
hyper-util = "*"
eyre = "*"

[lints]
workspace = true
